version: '3.8'

services:
  db:
    container_name: go_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5431:5431"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  be:
    image: goochadregistry.azurecr.io/be:latest
    build: ./server
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app
    command: go run ./cmd/api/main.go
    depends_on:
      - db

  fe:
    image: goochadregistry.azurecr.io/fe:latest
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - be


volumes:
  postgres-db: