# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          cd backend && go mod init backend
          go get github.com/lib/pq
          go get github.com/gorilla/mux
          go get github.com/gorilla/sessions
          go get github.com/stripe/stripe-go/v76
          go get gorm.io/gorm
          go get gorm.io/gorm/logger
          go get gorm.io/driver/postgres
          go get github.com/google/uuid
          go get github.com/joho/godotenv
          go get golang.org/x/lint/golint
          go get github.com/dgrijalva/jwt-go
          go get github.com/rs/cors
          go get golang.org/x/oauth2
          go get golang.org/x/oauth2/google

      - name: Build
        run: |
          cd backend
          go build -v ./...

      - name: Test
        run: |
          cd backend
          go test -v ./...

