name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    container:
      image: golangci/golangci-lint:latest
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Lint
        run: |
          cd backend 
          go mod init backend
          go get .
          go mod tidy
          golangci-lint run
          go vet .
